[render.yaml]
services:
  - type: web
    name: cheat-license-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production 
